[package]
name = "simple_nft"
version = "0.1.0"
edition = "2024.beta"
license = "MIT"
authors = ["Artitaya <contact@artitaya.dev>"]

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
simple_nft = "0x0"
sui = "0x2"